version: 1.0.{build}
install:
- cmd: >-
    dotnet restore

    npm install -g bower
build:
  verbosity: minimal
after_build:
- cmd: dotnet publish src\CoreWebApplication1 --output %appveyor_build_folder%\dist
artifacts:
- path: dist
  name: dist.web

before_deploy:
- ps: >-
    $username = "`$ilyaf4"

    $password = $env:sitepwd

    $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username,$password)))

    $destination = "app_offline.htm"

    $apiUrl = "https://ilyaf4.scm.azurewebsites.net/api/vfs/site/wwwroot/$destination"

    $filePath = "app_offline_tmp.htm"

    Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method PUT -InFile $filePath -ContentType "multipart/form-data"

deploy:
- provider: WebDeploy
  server: https://ilyaf4.scm.azurewebsites.net/msdeploy.axd?site=ilyaf
  website: ilyaf4
  username: $ilyaf4
  password:
    secure: 6Ld20wVhIzLd+G2PlkT90wZuM4DlJLCPy+hslN4FZwlC/+QL7YzpskuA9TOhJRPSFu77ya3d1GhmdBDz7J9WzA==
  artifact: dist.web
  aspnet_core: true
  aspnet_core_force_restart: true
  #app_offline: true
